### ISSUE TITLE
Support using latest as goss version

### ISSUE THREAD

**Issue by onedr0p** [e1himself/goss-installation-action#19]
Hi 👋🏼 

It would be a cool feature to allow setting the version to latest instead of pinning to a specific goss version, goss development is very slow and there shouldnt be any breaking changes. If there are it should be up whomever is using this action to accept that it could break using latest.

Thanks!

**Comment by e1himself** [comment]
Hey @onedr0p!

Thanks for the suggestion :+1: 

Even though this makes total sense, It's not clear to me how to download the latest release binaries from the *goss* Github page.  If there only was support for `/latest/` tag instead of specifying the exact version.

I'd be happy to hear any ideas on how to achieve this without overengineering the scripts.

Thanks!

**Comment by onedr0p** [comment]
Thanks!

**Comment by e1himself** [comment]
Hey @onedr0p!

The action now supports `latest` as the version specifier (and so by default). 

Please check if it works to confirm it's all good. 

Thanks! :raised_hands:
